import { STORAGE_BASE_URL } from './api';

/**
 * Get the full URL for a stored file.
 * 
 * When MinIO is configured with a public bucket, the backend returns
 * the MinIO URL directly. Otherwise, the download URL is a presigned
 * URL generated by the backend.
 */
export function getFileUrl(storagePath: string): string {
  // If storagePath is already a full URL, return it as-is
  if (storagePath.startsWith('http://') || storagePath.startsWith('https://')) {
    return storagePath;
  }
  
  // Otherwise, construct the URL from the storage base
  // This handles both MinIO URLs and local storage proxy URLs
  return `${STORAGE_BASE_URL}/storage/${encodeURIComponent(storagePath)}`;
}

/**
 * Download a file from storage.
 * 
 * @param storagePath - The storage path of the file
 * @param fileName - Optional filename for the download dialog
 */
export function downloadFile(storagePath: string, fileName?: string): void {
  const url = getFileUrl(storagePath);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName || extractFileName(storagePath);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Open a file in a new tab (for images, PDFs, etc.)
 */
export function openFile(storagePath: string): void {
  const url = getFileUrl(storagePath);
  window.open(url, '_blank');
}

/**
 * Check if a storage path is an image
 */
export function isImageFile(storagePath: string): boolean {
  const ext = storagePath.split('.').pop()?.toLowerCase();
  return ['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif'].includes(ext || '');
}

/**
 * Check if a storage path is a PDF
 */
export function isPdfFile(storagePath: string): boolean {
  const ext = storagePath.split('.').pop()?.toLowerCase();
  return ext === 'pdf';
}

function extractFileName(storagePath: string): string {
  const parts = storagePath.split('/');
  return parts[parts.length - 1] || 'download';
}
